config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "tasks#index"

  get "tasks", to: "tasks#index" # Read all
  get "tasks/new", to: "tasks#new" # Create
  get "tasks/:id", to: "tasks#show", as: :task # Read one
  post "tasks", to: "tasks#create"
  get "tasks/:id/edit", to: "tasks#edit", as: :edit # Select one to update
  patch "tasks/:id", to: "tasks#update" # update
  delete "tasks/:id", to: "tasks#destroy" # Delete
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def index
		@task = Task.all
	end

	def show
		@task = Task.find(params[:id])
	end

	def new
		@task = Task.new
	end

	def create
		@task = Task.new(tasks_params)
		@task.save
		redirect_to tasks_path(@task)
	end

	def edit
		@task = Task.find(params[:id])
	end

	def update
    @task = Task.find(params[:id])
    @task.update(tasks_params)
    redirect_to tasks_path(@task)
	end

	def destroy
		@task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path(@task)
	end

	private

  def tasks_params
    params.require(:task).permit(:title, :detail, :completed) # :task fait appel à quoi?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta charset="utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel=“stylesheet” href=“https://use.fontawesome.com/releases/v5.0.10/css/all.css”>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :detail %>
  <%= f.text_field :detail %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1>Index</h1>

<ul>
  <% @task.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
    <p><%= link_to 'Delete !', task_path(id: task.id), method: :delete, data: { confirm: "Are you sure?" } %></p>

    <% if task.completed %>
      <i class="fa fa-check-square"></i>
    <% else %>
      <i class="fa fa-square"></i>
    <% end %>
  <% end %>
</ul>
<br>
<%= link_to "+ Add a new task", tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Create</h1>

<%= form_for (@task) do |f| %>
	<%= f.label :title %>
	<%= f.text_field :title %>
	<br>
	<br>
	<%= f.label :detail %>
  <%= f.text_field :detail %>
  <br>
  <br>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "Back to index", tasks_path %>

app/views/tasks/show.html.erb
<h1>Show</h1>

<%= @task.title %>
<br>
<%= @task.detail %>
<br>
<%= @task.completed %>
<br>
<%= link_to 'Edit !', edit_path(@task) %>
<br>
<%= link_to "Back to index", tasks_path %>